image: docker:latest
services:
  - docker:dind
before_script:
  - apk add --update curl && rm -rf /var/cache/apk/*
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
tag-build:
  stage: build
  only:
    - tags
    - triggers
  script:
    # Build image
    - docker build -t "docker-image" .
    - docker tag "docker-image" "registry.gitlab.com/relightings/public/tools/docker/terraform/aws:latest"
    - docker tag "docker-image" "registry.gitlab.com/relightings/public/tools/docker/terraform/aws:$CI_COMMIT_TAG"
    
    # Push Gitlab Registry
    - docker images
    - docker push "registry.gitlab.com/relightings/public/tools/docker/terraform/aws:latest"
    - docker push "registry.gitlab.com/relightings/public/tools/docker/terraform/aws:$CI_COMMIT_TAG"
  tags:
    - docker
