version: '3.9'
services:
  lxc:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ['/usr/sbin/squid']
    command: ["-N", "-f", "/etc/squid/squid.conf"]
    container_name: squid
    tty: true
    ports:
      - "3128:3128"
    volumes:
      - ./squid.conf:/etc/squid/squid.conf
      - ./lxc-whitelist:/etc/squid/whitelist
    restart: always
