name: Build and Publish Docker

on:
  push:
    tags:
      - squid-v*

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      REPO_OWNER: ${{ github.repository_owner }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ env.REPO_OWNER }}
          password: ${{ secrets.CR_PAT }}

      - name: Get the version
        id: get_version
        run: |-
          echo ::set-output name=LXC_NAME::$(echo ${GITHUB_REF} | sed -e 's#refs/tags/##g' | awk -F'-' '{print $1}')
          echo ::set-output name=LXC_VERSION::$(echo ${GITHUB_REF} | sed -e 's#refs/tags/##g' | awk -F'-' '{print $2}')

      - name: Push image to GitHub Container Registry
        uses: docker/build-push-action@v2
        working-directory: ./proxy/${{ steps.get_version.outputs.LXC_NAME }}
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER }}/${{ steps.get_version.outputs.LXC_NAME }}:latest
            ghcr.io/${{ env.REPO_OWNER }}/${{ steps.get_version.outputs.LXC_NAME }}:${{ steps.get_version.outputs.LXC_VERSION }}
