name: Build and Publish Docker

on:
  push:
    tags:
      - squid-v*
      - airflow2-v*
      - litespeed-v*
      - tfaws-v*
      - tfgcp-v*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REPO_OWNER: ${{ github.repository_owner }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.REPO_OWNER }}
          password: ${{ secrets.CR_PAT }}

      - name: Get the version
        id: get_version
        run: echo VERSION=$(echo ${GITHUB_REF} | sed -e 's#refs/tags/##g' | awk -F'-' '{print $2}') >> $GITHUB_ENV

      - name: "[ghcr.io/${{ env.REPO_OWNER }}/squid-lxc] Push image to GitHub Container Registry"
        if: contains(github.ref, 'tags/squid-v')
        uses: docker/build-push-action@v5
        env:
          DOCKER_CONTENT_TRUST: 1
          BUILDKIT_MULTI_PLATFORM: 1
        with:
          platforms: linux/amd64,linux/arm64
          context: ./proxy/squid
          push: true
          provenance: false
          tags: ghcr.io/${{ env.REPO_OWNER }}/squid-lxc:latest,ghcr.io/${{ env.REPO_OWNER }}/squid-lxc:${{ env.VERSION }}

      - name: "[ghcr.io/[${{ env.REPO_OWNER }}/airflow2] Push image to GitHub Container Registry"
        if: contains(github.ref, 'tags/airflow2-v')
        uses: docker/build-push-action@v5
        env:
          DOCKER_CONTENT_TRUST: 1
          BUILDKIT_MULTI_PLATFORM: 1
        with:
          platforms: linux/amd64,linux/arm64
          context: ./web/airflow
          push: true
          provenance: false
          tags: ghcr.io/${{ env.REPO_OWNER }}/airflow2:latest,ghcr.io/${{ env.REPO_OWNER }}/airflow2:${{ env.VERSION }}

      - name: "[ghcr.io/${{ env.REPO_OWNER }}/litespeed] Push image to GitHub Container Registry"
        if: contains(github.ref, 'tags/litespeed-v')
        uses: docker/build-push-action@v5
        env:
          DOCKER_CONTENT_TRUST: 1
          BUILDKIT_MULTI_PLATFORM: 1
        with:
          platforms: linux/amd64,linux/arm64
          context: ./web/litespeed
          push: true
          provenance: false
          tags: ghcr.io/${{ env.REPO_OWNER }}/litespeed:latest,ghcr.io/${{ env.REPO_OWNER }}/litespeed:${{ env.VERSION }}

      - name: "[ghcr.io/${{ env.REPO_OWNER }}/tfaws] Push image to GitHub Container Registry"
        if: contains(github.ref, 'tags/tfaws-v')
        uses: docker/build-push-action@v5
        env:
          DOCKER_CONTENT_TRUST: 1
          BUILDKIT_MULTI_PLATFORM: 1
        with:
          platforms: linux/amd64,linux/arm64
          context: ./terraform/aws
          push: true
          provenance: false
          tags: ghcr.io/${{ env.REPO_OWNER }}/terraform-aws:latest,ghcr.io/${{ env.REPO_OWNER }}/terraform-aws:${{ env.VERSION }}

      - name: "[ghcr.io/${{ env.REPO_OWNER }}/tfgcp] Push image to GitHub Container Registry"
        if: contains(github.ref, 'tags/tfgcp-v')
        uses: docker/build-push-action@v5
        env:
          DOCKER_CONTENT_TRUST: 1
          BUILDKIT_MULTI_PLATFORM: 1
        with:
          platforms: linux/amd64,linux/arm64
          context: ./terraform/gcp
          push: true
          provenance: false
          tags: ghcr.io/${{ env.REPO_OWNER }}/terraform-gcp:latest,ghcr.io/${{ env.REPO_OWNER }}/terraform-gcp:${{ env.VERSION }}
