name: Build and Publish Docker

on:
  push:
    tags:
      - squid-v*
      - airflow2-v*
      - litespeed-v*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REPO_OWNER: ${{ github.repository_owner }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ env.REPO_OWNER }}
          password: ${{ secrets.CR_PAT }}

      - name: Get the version
        id: get_version
        run: |-
          echo ::set-output name=VERSION::$(echo ${GITHUB_REF} | sed -e 's#refs/tags/##g' | awk -F'-' '{print $2}')

      - name: "[ghcr.io/${{ env.REPO_OWNER }}/squid-lxc] Push image to GitHub Container Registry"
        if: contains(github.ref, 'tags/squid-v')
        uses: docker/build-push-action@v2
        env:
          DOCKER_CONTENT_TRUST: 1
        with:
          context: ./proxy/squid
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER }}/squid-lxc:latest
            ghcr.io/${{ env.REPO_OWNER }}/squid-lxc:${{ steps.get_version.outputs.VERSION }}

      - name: "[ghcr.io/${{ env.REPO_OWNER }}/airflow2] Push image to GitHub Container Registry"
        if: contains(github.ref, 'tags/airflow2-v')
        uses: docker/build-push-action@v2
        env:
          DOCKER_CONTENT_TRUST: 1
        with:
          context: ./web/airflow
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER }}/airflow2:latest
            ghcr.io/${{ env.REPO_OWNER }}/airflow2:${{ steps.get_version.outputs.VERSION }}

      - name: "[ghcr.io/${{ env.REPO_OWNER }}/litespeed] Push image to GitHub Container Registry"
        if: contains(github.ref, 'tags/litespeed-v')
        uses: docker/build-push-action@v2
        env:
          DOCKER_CONTENT_TRUST: 1
        with:
          context: ./web/litespeed
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER }}/litespeed:latest
            ghcr.io/${{ env.REPO_OWNER }}/litespeed:${{ steps.get_version.outputs.VERSION }}
